
import { getTop100Cryptos } from '@/lib/coingecko';
import CryptoDetailView from '@/components/crypto-detail-view';

export async function generateStaticParams() {
    const cryptos = await getTop100Cryptos();

    // If the API call fails or returns no data,
    // fallback to generating a page for Bitcoin to ensure the build doesn't fail.
    if (!cryptos || cryptos.length === 0) {
        return [
  { id: 'bitcoin' },
  { id: 'ethereum' },
  { id: 'tether' },
  { id: 'ripple' },
  { id: 'binancecoin' },
  { id: 'solana' },
  { id: 'usd-coin' },
  { id: 'tron' },
  { id: 'dogecoin' },
  { id: 'staked-ether' },
  { id: 'cardano' },
  { id: 'wrapped-bitcoin' },
  { id: 'hyperliquid' },
  { id: 'wrapped-steth' },
  { id: 'sui' },
  { id: 'bitcoin-cash' },
  { id: 'chainlink' },
  { id: 'leo-token' },
  { id: 'stellar' },
  { id: 'avalanche-2' },
  { id: 'usds' },
  { id: 'the-open-network' },
  { id: 'whitebit' },
  { id: 'shiba-inu' },
  { id: 'hedera-hashgraph' },
  { id: 'litecoin' },
  { id: 'weth' },
  { id: 'wrapped-eeth' },
  { id: 'binance-bridged-usdt-bnb-smart-chain' },
  { id: 'monero' },
  { id: 'ethena-usde' },
  { id: 'polkadot' },
  { id: 'bitget-token' },
  { id: 'coinbase-wrapped-btc' },
  { id: 'pi-network' },
  { id: 'uniswap' },
  { id: 'pepe' },
  { id: 'aave' },
  { id: 'dai' },
  { id: 'ethena-staked-usde' },
  { id: 'aptos' },
  { id: 'okb' },
  { id: 'bittensor' },
  { id: 'blackrock-usd-institutional-digital-liquidity-fund' },
  { id: 'near' },
  { id: 'susds' },
  { id: 'internet-computer' },
  { id: 'jito-staked-sol' },
  { id: 'crypto-com-chain' },
  { id: 'ethereum-classic' },
  { id: 'ondo-finance' },
  { id: 'tokenize-xchange' },
  { id: 'usd1-wlfi' },
  { id: 'mantle' },
  { id: 'gatechain-token' },
  { id: 'kaspa' },
  { id: 'fasttoken' },
  { id: 'official-trump' },
  { id: 'cosmos' },
  { id: 'vechain' },
  { id: 'sky' },
  { id: 'fetch-ai' },
  { id: 'sei-network' },
  { id: 'lombard-staked-btc' },
  { id: 'render-token' },
  { id: 'polygon-ecosystem-token' },
  { id: 'ethena' },
  { id: 'algorand' },
  { id: 'filecoin' },
  { id: 'arbitrum' },
  { id: 'first-digital-usd' },
  { id: 'worldcoin-wld' },
  { id: 'jupiter-perpetuals-liquidity-provider-token' },
  { id: 'binance-peg-weth' },
  { id: 'usdtb' },
  { id: 'quant-network' },
  { id: 'kucoin-shares' },
  { id: 'binance-staked-sol' },
  { id: 'usdt0' },
  { id: 'spx6900' },
  { id: 'jupiter-exchange-solana' },
  { id: 'nexo' },
  { id: 'flare-networks' },
  { id: 'kaia' },
  { id: 'rocket-pool-eth' },
  { id: 'kelp-dao-restaked-eth' },
  { id: 'celestia' },
  { id: 'injective-protocol' },
  { id: 'blockstack' },
  { id: 'fartcoin' },
  { id: 'bonk' },
  { id: 'sonic-3' },
  { id: 'virtual-protocol' },
  { id: 'polygon-bridged-usdt-polygon' },
  { id: 'binance-bridged-usdc-bnb-smart-chain' },
  { id: 'optimism' },
  { id: 'xdce-crowd-sale' },
  { id: 'paypal-usd' },
  { id: 'mantle-staked-ether' },
  { id: 'solv-btc' }
];
    }

    return cryptos.map((crypto) => ({
        id: crypto.id,
    }));
}

export default function CryptoDetailPage() {
    return <CryptoDetailView />;
}
